### ISSUE TITLE
Update code to remove inline styling and add theme support.

### ISSUE THREAD

**Issue by slm4996** [osTicket/osTicket#490]
How receptive would you (the core developers) be to a few commits to remove the inline styling, update the core theme to bootstrap 3, and to add client and staff theme support? 

I don't mind putting in the work, but only if it's something that would be considered for a merge to a release.
## Tasks to complete this issue:
- [ ] Remove inline styles
- [ ] Convert core theme to Bootstrap 3
- [ ] Add client side them support
- [ ] Add Staff side theme support

**Comment by fproject** [comment]
+1

**Comment by ddan39** [comment]
What ever happened to the work on this? Are the changes slm4996 made available somewhere so it can be finished? This is the one thing missing that is going to make us switch away from osticket soon. Many customers are trying to access it from their phones.

**Comment by JediKev** [comment]
@ddan39 

This is something we are looking at tackling after version 2.0 is released. Please stay tuned!
